---
- name: Check for supported distros should be made
  fail:
    msg: "Distro {{ ansible_distribution }} is not supported yet."
  when: ansible_os_family not in graylog_supported_os_families

- name: OS-family specific vars should be loaded
  include_vars: "{{ ansible_os_family }}.yml"

- set_fact: use_system_d={{(ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>=')) }}

- include: "mongodb-{{ ansible_os_family }}.yml"

- include: "java-{{ ansible_os_family }}.yml"

- include: "setup-{{ ansible_os_family }}.yml"

- include: server.yml
