---

- name: "Check for supported distribution"
  fail:
    msg: "Distro {{ ansible_distribution }} is not supported yet."
  when: ansible_os_family not in graylog_supported_os_families

- name: "Check required variables"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{ required_vars }}"

- name: "Check graylog_mongodb_version var"
  fail: msg="The 'graylog_mongodb_version' variable is not defined."
  when: (graylog_install_mongodb) and (graylog_mongodb_version is not defined)

- name: "Check deprecated variables: graylog_server_version"
  fail:
    msg: "Variable 'graylog_server_version' has been deprecated. Use 'graylog_full_version' instead."
  when: graylog_server_version is defined

- name: "Check deprecated variables: graylog_install_nginx"
  fail:
    msg: "Varible 'graylog_install_nginx' has been deprecated. Use the official Nginx role to install Nginx."
  when: graylog_install_nginx is defined

- name: "Load OS-family specific vars"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Discover systemd capabilities"
  set_fact:
    use_system_d: >
      {{
        (ansible_distribution == 'Debian' and ansible_distribution_version is version('8', '>=')) or
        (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version is version('7', '>=')) or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('15', '>='))
      }}

- include: "mongodb-{{ ansible_os_family }}.yml"
  when: graylog_install_mongodb

- include: "setup-{{ ansible_os_family }}.yml"

- include: "server.yml"
