---
- name: Repositories should be updated
  yum_repository:
    name: "mongodb-org"
    description: "MongoDB Repository"
    baseurl: "{{ graylog_mongodb_redhat_repo }}"
    gpgkey: "{{ graylog_mongodb_redhat_key }}"
    gpgcheck: yes
    enabled: yes
  when:
    - ansible_distribution in ['RedHat','CentOS']
    - graylog_install_mongodb

- name: MongoDB should be installed
  yum:
    name: "mongodb-org"
    state: present
  when:
    - ansible_distribution in ['RedHat','CentOS']
    - graylog_install_mongodb

- name: MongoDB should be configured
  template:
    src: 'mongodb.conf.j2'
    dest: "/etc/mongod.conf"
    owner: root
    group: root
    mode: '0644'
  when: graylog_install_mongodb
  notify: restart mongod

- meta: flush_handlers
- name: Wait for MongoDB to startup
  wait_for: host=127.0.0.1 port=27017 delay=5 connect_timeout=1
