---

- name: Install python-software-properties
  apt: name=python-software-properties state=present

- name: Update repositories
  apt_repository: repo={{ java_ppa }} state=present update_cache=yes
  when: ansible_distribution == "Ubuntu"

- name: Update repositories
  apt_repository: repo="{{ item }}" state=present update_cache=yes
  with_items:
    - "{{ java_repo }}"
    - "{{ java_src_repo }}"
  when: ansible_distribution == "Debian"

- name: Accept apt key for java repo
  apt_key: keyserver={{ java_repo_keyserver }} id={{ java_repo_key }}
  when: ansible_distribution == "Debian"

- name: Accept Oracle license prior JDK installation
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections creates=/usr/lib/jvm/java-8-oracle

- name: Install Java 8
  apt: name=oracle-java8-installer state=present force=yes

- name: Download Graylog repository package
  get_url: url={{ graylog_packages_url }} dest=/tmp/graylog_repository.deb

- apt: name=apt-transport-https state=installed

- name: Install Graylog repository
  apt: deb=/tmp/graylog_repository.deb state=installed dpkg_options='force-all'
  register: install_repo

- apt: update_cache=yes
  when: install_repo.changed == True
