---

- name: "Repositories should be updated"
  yum:
    name: "{{ graylog_yum_rpm_url }}"
    state: "present"
    update_cache: True
  when: graylog_manage_yum_repo

- name: "Graylog server should be installed"
  yum:
    name: "graylog-server{% if graylog_version is defined %}-{{ graylog_version }}{% endif %}"
    state: "{{ graylog_package_state }}"
  notify: restart graylog-server
