---

- name: "Repositories should be updated"
  yum:
    name: "{{ graylog_yum_rpm_url }}"
    state: "present"
    update_cache: True
  when: graylog_manage_yum_repo

- name: "Graylog server should be installed"
  yum:
    name: "graylog-server{% if graylog_full_version is defined %}-{{ graylog_full_version }}{% endif %}"
    state: "{{ graylog_package_state }}"
  notify: restart graylog-server

- name: "Installing graylog-enterprise-plugins"
  yum:
    name: "graylog-enterprise-plugins{% if graylog_full_version is defined %}-{{ graylog_full_version }}{% endif %}"
    state: "{{ graylog_package_state }}"
  when: graylog_install_enterprise_plugins
  notify: restart graylog-server

- name: "Installing graylog-integrations-plugins"
  yum:
    name: "graylog-integrations-plugins{% if graylog_full_version is defined %}-{{ graylog_full_version }}{% endif %}"
    state: "{{ graylog_package_state }}"
  when: graylog_install_integrations_plugins
  notify: restart graylog-server

- name: "Installing graylog-enterprise-integrations-plugins"
  yum:
    name: "graylog-enterprise-integrations-plugins{% if graylog_full_version is defined %}-{{ graylog_full_version }}{% endif %}"
    state: "{{ graylog_package_state }}"
  when: graylog_install_enterprise_integrations_plugins
  notify: restart graylog-server
